function [ys_, params, info] = steadystate(ys_, exo_, params)
% Steady state generated by Dynare preprocessor
    info = 0;
    r_ss=(1-params(2))/params(2);
    ys_(5)=params(5);
    ys_(6)=params(6);
    ys_(4)=ys_(5)/ys_(6);
    ys_(3)=params(4)/(ys_(5)+params(4));
    ys_(2)=ys_(4)*ys_(3);
    ys_(2)=ys_(4)*ys_(3);
    k_ss=(1-params(7))*(params(1)-params(8))/((r_ss+params(4))/params(6)+ys_(4)*params(7));
    ys_(1)=params(7)*(params(1)+ys_(4)*k_ss)+(1-params(7))*params(8);
    ys_(7)=0;
    x_imp=0;
    ys_(9)=0;
    ys_(10)=0;
    % Auxiliary equations
end
