%
% Status : main Dynare file 
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

clear all
tic;
global M_ oo_ options_ ys0_ ex0_ estimation_info
options_ = [];
M_.fname = 'model';
%
% Some global variables initialization
%
global_initialization;
diary off;
diary('model.log');
M_.exo_names = 'e_z';
M_.exo_names_tex = '{e_z}';
M_.exo_names_long = 'Technology shock';
M_.exo_names = char(M_.exo_names, 'e_s');
M_.exo_names_tex = char(M_.exo_names_tex, '{e_s}');
M_.exo_names_long = char(M_.exo_names_long, 'Job separation shock');
M_.exo_names = char(M_.exo_names, 'e_delta');
M_.exo_names_tex = char(M_.exo_names_tex, '{e_\delta}');
M_.exo_names_long = char(M_.exo_names_long, 'Firm destruction shock');
M_.endo_names = 'theta';
M_.endo_names_tex = '{theta}';
M_.endo_names_long = 'Market tightness';
M_.endo_names = char(M_.endo_names, 'f');
M_.endo_names_tex = char(M_.endo_names_tex, '{f}');
M_.endo_names_long = char(M_.endo_names_long, 'Job finding rate');
M_.endo_names = char(M_.endo_names, 'q');
M_.endo_names_tex = char(M_.endo_names_tex, '{q}');
M_.endo_names_long = char(M_.endo_names_long, 'Vacancy filling rate');
M_.endo_names = char(M_.endo_names, 'p');
M_.endo_names_tex = char(M_.endo_names_tex, '{p}');
M_.endo_names_long = char(M_.endo_names_long, 'Relative price');
M_.endo_names = char(M_.endo_names, 'lam');
M_.endo_names_tex = char(M_.endo_names_tex, '{\lambda}');
M_.endo_names_long = char(M_.endo_names_long, 'Marginal utility of consumption');
M_.endo_names = char(M_.endo_names, 'nu');
M_.endo_names_tex = char(M_.endo_names_tex, '{nu}');
M_.endo_names_long = char(M_.endo_names_long, 'Retailer firm value');
M_.endo_names = char(M_.endo_names, 'd');
M_.endo_names_tex = char(M_.endo_names_tex, '{d}');
M_.endo_names_long = char(M_.endo_names_long, 'Dividend');
M_.endo_names = char(M_.endo_names, 'Ne');
M_.endo_names_tex = char(M_.endo_names_tex, '{N^{e}}');
M_.endo_names_long = char(M_.endo_names_long, 'Number of new businesses');
M_.endo_names = char(M_.endo_names, 'K');
M_.endo_names_tex = char(M_.endo_names_tex, '{K}');
M_.endo_names_long = char(M_.endo_names_long, 'Expected discounted difference in vacancy value');
M_.endo_names = char(M_.endo_names, 'Q');
M_.endo_names_tex = char(M_.endo_names_tex, '{Q}');
M_.endo_names_long = char(M_.endo_names_long, 'Value of vacancy');
M_.endo_names = char(M_.endo_names, 'e');
M_.endo_names_tex = char(M_.endo_names_tex, '{e}');
M_.endo_names_long = char(M_.endo_names_long, 'New vacancies');
M_.endo_names = char(M_.endo_names, 'wint');
M_.endo_names_tex = char(M_.endo_names_tex, '{w^(int)}');
M_.endo_names_long = char(M_.endo_names_long, 'Recruiter payment');
M_.endo_names = char(M_.endo_names, 'w');
M_.endo_names_tex = char(M_.endo_names_tex, '{w}');
M_.endo_names_long = char(M_.endo_names_long, 'Wage');
M_.endo_names = char(M_.endo_names, 'N');
M_.endo_names_tex = char(M_.endo_names_tex, '{N}');
M_.endo_names_long = char(M_.endo_names_long, 'Number of firms');
M_.endo_names = char(M_.endo_names, 'u');
M_.endo_names_tex = char(M_.endo_names_tex, '{u}');
M_.endo_names_long = char(M_.endo_names_long, 'Unemployment');
M_.endo_names = char(M_.endo_names, 'v');
M_.endo_names_tex = char(M_.endo_names_tex, '{v}');
M_.endo_names_long = char(M_.endo_names_long, 'Vacancy stock');
M_.endo_names = char(M_.endo_names, 'tau');
M_.endo_names_tex = char(M_.endo_names_tex, '{\tau');
M_.endo_names_long = char(M_.endo_names_long, 'Aggregate separation rate');
M_.endo_names = char(M_.endo_names, 'L');
M_.endo_names_tex = char(M_.endo_names_tex, '{L}');
M_.endo_names_long = char(M_.endo_names_long, 'Total labor');
M_.endo_names = char(M_.endo_names, 'Le');
M_.endo_names_tex = char(M_.endo_names_tex, '{L^{e}}');
M_.endo_names_long = char(M_.endo_names_long, 'Labor in entry');
M_.endo_names = char(M_.endo_names, 'Lc');
M_.endo_names_tex = char(M_.endo_names_tex, '{L^{c}}');
M_.endo_names_long = char(M_.endo_names_long, 'Labor in consumption');
M_.endo_names = char(M_.endo_names, 'X');
M_.endo_names_tex = char(M_.endo_names_tex, '{X}');
M_.endo_names_long = char(M_.endo_names_long, 'Hiring cost');
M_.endo_names = char(M_.endo_names, 'C');
M_.endo_names_tex = char(M_.endo_names_tex, '{C}');
M_.endo_names_long = char(M_.endo_names_long, 'Consumption');
M_.endo_names = char(M_.endo_names, 'Yc');
M_.endo_names_tex = char(M_.endo_names_tex, '{Y^{c}}');
M_.endo_names_long = char(M_.endo_names_long, 'Retail output');
M_.endo_names = char(M_.endo_names, 'Ygross');
M_.endo_names_tex = char(M_.endo_names_tex, '{Y^{Gross}}');
M_.endo_names_long = char(M_.endo_names_long, 'Gross output');
M_.endo_names = char(M_.endo_names, 'Y');
M_.endo_names_tex = char(M_.endo_names_tex, '{Y}');
M_.endo_names_long = char(M_.endo_names_long, 'Net output');
M_.endo_names = char(M_.endo_names, 'ls');
M_.endo_names_tex = char(M_.endo_names_tex, '{\ell s}');
M_.endo_names_long = char(M_.endo_names_long, 'Labor share');
M_.endo_names = char(M_.endo_names, 'lp');
M_.endo_names_tex = char(M_.endo_names_tex, '{\ell p}');
M_.endo_names_long = char(M_.endo_names_long, 'Labor productivity');
M_.endo_names = char(M_.endo_names, 'z');
M_.endo_names_tex = char(M_.endo_names_tex, '{z}');
M_.endo_names_long = char(M_.endo_names_long, 'Tech shocks');
M_.endo_names = char(M_.endo_names, 's');
M_.endo_names_tex = char(M_.endo_names_tex, '{s}');
M_.endo_names_long = char(M_.endo_names_long, 'Separation shocks');
M_.endo_names = char(M_.endo_names, 'delta');
M_.endo_names_tex = char(M_.endo_names_tex, '{\delta}');
M_.endo_names_long = char(M_.endo_names_long, 'Product destruction shocks');
M_.endo_names = char(M_.endo_names, 'u_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'u\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'u_obs');
M_.endo_names = char(M_.endo_names, 'v_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'v\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'v_obs');
M_.endo_names = char(M_.endo_names, 'tau_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'tau\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'tau_obs');
M_.endo_names = char(M_.endo_names, 'f_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'f\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'f_obs');
M_.endo_names = char(M_.endo_names, 'delta_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'delta\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'delta_obs');
M_.endo_names = char(M_.endo_names, 'bf_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'bf\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'bf_obs');
M_.endo_names = char(M_.endo_names, 'lp_obs');
M_.endo_names_tex = char(M_.endo_names_tex, 'lp\_obs');
M_.endo_names_long = char(M_.endo_names_long, 'lp_obs');
M_.endo_names = char(M_.endo_names, 'u_obs_lag');
M_.endo_names_tex = char(M_.endo_names_tex, 'u\_obs\_lag');
M_.endo_names_long = char(M_.endo_names_long, 'u_obs_lag');
M_.endo_names = char(M_.endo_names, 'v_obs_lag');
M_.endo_names_tex = char(M_.endo_names_tex, 'v\_obs\_lag');
M_.endo_names_long = char(M_.endo_names_long, 'v_obs_lag');
M_.endo_names = char(M_.endo_names, 'tau_obs_lag');
M_.endo_names_tex = char(M_.endo_names_tex, 'tau\_obs\_lag');
M_.endo_names_long = char(M_.endo_names_long, 'tau_obs_lag');
M_.endo_names = char(M_.endo_names, 'f_obs_lag');
M_.endo_names_tex = char(M_.endo_names_tex, 'f\_obs\_lag');
M_.endo_names_long = char(M_.endo_names_long, 'f_obs_lag');
M_.endo_names = char(M_.endo_names, 'delta_obs_lag');
M_.endo_names_tex = char(M_.endo_names_tex, 'delta\_obs\_lag');
M_.endo_names_long = char(M_.endo_names_long, 'delta_obs_lag');
M_.endo_names = char(M_.endo_names, 'bf_obs_lag');
M_.endo_names_tex = char(M_.endo_names_tex, 'bf\_obs\_lag');
M_.endo_names_long = char(M_.endo_names_long, 'bf_obs_lag');
M_.endo_names = char(M_.endo_names, 'lp_obs_lag');
M_.endo_names_tex = char(M_.endo_names_tex, 'lp\_obs\_lag');
M_.endo_names_long = char(M_.endo_names_long, 'lp_obs_lag');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_14_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_14\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_14_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_15_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_15\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_15_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_16_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_16\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_16_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_29_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_29\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_29_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_1_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_1\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_1_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_7_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_7\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_7_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_26_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_26\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_26_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_30_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_30\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_30_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_30_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_30\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_30_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_31_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_31\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_31_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_31_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_31\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_31_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_32_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_32\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_32_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_32_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_32\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_32_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_33_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_33\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_33_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_33_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_33\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_33_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_34_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_34\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_34_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_34_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_34\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_34_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_35_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_35\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_35_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_35_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_35\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_35_2');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_36_1');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_36\_1');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_36_1');
M_.endo_names = char(M_.endo_names, 'AUX_ENDO_LAG_36_2');
M_.endo_names_tex = char(M_.endo_names_tex, 'AUX\_ENDO\_LAG\_36\_2');
M_.endo_names_long = char(M_.endo_names_long, 'AUX_ENDO_LAG_36_2');
M_.param_names = 'sigma';
M_.param_names_tex = '{\sigma}';
M_.param_names_long = 'Inverse of intertemporal elasticity of substitution';
M_.param_names = char(M_.param_names, 'b_ratio');
M_.param_names_tex = char(M_.param_names_tex, '{b_{ratio}}');
M_.param_names_long = char(M_.param_names_long, 'Replacement ratio: unemployment benefits to wages');
M_.param_names = char(M_.param_names, 'xi_inv');
M_.param_names_tex = char(M_.param_names_tex, '{\xi_{inv}}');
M_.param_names_long = char(M_.param_names_long, 'Inverse elasticity of entrants to vacancy value');
M_.param_names = char(M_.param_names, 'x_v');
M_.param_names_tex = char(M_.param_names_tex, '{x_{v}}');
M_.param_names_long = char(M_.param_names_long, 'Share of flow costs from vacancy creation');
M_.param_names = char(M_.param_names, 'rho_z');
M_.param_names_tex = char(M_.param_names_tex, '{\rho_z}');
M_.param_names_long = char(M_.param_names_long, 'Persistence of tech shocks');
M_.param_names = char(M_.param_names, 'rho_s');
M_.param_names_tex = char(M_.param_names_tex, '{\rho_s}');
M_.param_names_long = char(M_.param_names_long, 'Persistence of separation shocks');
M_.param_names = char(M_.param_names, 'rho_delta');
M_.param_names_tex = char(M_.param_names_tex, '{\rho_delta}');
M_.param_names_long = char(M_.param_names_long, 'Persistence of product destruction shocks');
M_.param_names = char(M_.param_names, 'sigma_z');
M_.param_names_tex = char(M_.param_names_tex, '{\sigma_z}');
M_.param_names_long = char(M_.param_names_long, 'Std. dev of tech shocks');
M_.param_names = char(M_.param_names, 'sigma_s');
M_.param_names_tex = char(M_.param_names_tex, '{\sigma_s}');
M_.param_names_long = char(M_.param_names_long, 'std. dev of separation shocks');
M_.param_names = char(M_.param_names, 'sigma_delta');
M_.param_names_tex = char(M_.param_names_tex, '{\sigma_delta}');
M_.param_names_long = char(M_.param_names_long, 'Std. dev of prod. dest. shocks');
M_.param_names = char(M_.param_names, 'eta');
M_.param_names_tex = char(M_.param_names_tex, '{\eta}');
M_.param_names_long = char(M_.param_names_long, 'Elasticity of matching function with respect to unemployment');
M_.param_names = char(M_.param_names, 'F');
M_.param_names_tex = char(M_.param_names_tex, '{F}');
M_.param_names_long = char(M_.param_names_long, 'Parameter of vacancy creation');
M_.param_names = char(M_.param_names, 'epsi');
M_.param_names_tex = char(M_.param_names_tex, '{\varepsilon}');
M_.param_names_long = char(M_.param_names_long, 'Elasticity of substitution');
M_.param_names = char(M_.param_names, 'zeta');
M_.param_names_tex = char(M_.param_names_tex, '\zeta');
M_.param_names_long = char(M_.param_names_long, 'Love for variety');
M_.param_names = char(M_.param_names, 'XY');
M_.param_names_tex = char(M_.param_names_tex, 'XY');
M_.param_names_long = char(M_.param_names_long, 'Share of hiring cost in GDP');
M_.param_names = char(M_.param_names, 'beta');
M_.param_names_tex = char(M_.param_names_tex, '{\beta}');
M_.param_names_long = char(M_.param_names_long, 'Discount factor');
M_.param_names = char(M_.param_names, 'kappa');
M_.param_names_tex = char(M_.param_names_tex, '{\kappa}');
M_.param_names_long = char(M_.param_names_long, 'Cost of job posting');
M_.param_names = char(M_.param_names, 'f_e');
M_.param_names_tex = char(M_.param_names_tex, '{f_e}');
M_.param_names_long = char(M_.param_names_long, 'Cost of business creation');
M_.param_names = char(M_.param_names, 'A');
M_.param_names_tex = char(M_.param_names_tex, '{A}');
M_.param_names_long = char(M_.param_names_long, 'Match efficiency');
M_.param_names = char(M_.param_names, 'x_m');
M_.param_names_tex = char(M_.param_names_tex, '{x_{m}}');
M_.param_names_long = char(M_.param_names_long, 'Cost of job creation');
M_.param_names = char(M_.param_names, 'phi');
M_.param_names_tex = char(M_.param_names_tex, '{\phi}');
M_.param_names_long = char(M_.param_names_long, 'Bargaining power');
M_.exo_det_nbr = 0;
M_.exo_nbr = 3;
M_.endo_nbr = 65;
M_.param_nbr = 21;
M_.orig_endo_nbr = 44;
M_.aux_vars(1).endo_index = 45;
M_.aux_vars(1).type = 1;
M_.aux_vars(1).orig_index = 15;
M_.aux_vars(1).orig_lead_lag = -1;
M_.aux_vars(2).endo_index = 46;
M_.aux_vars(2).type = 1;
M_.aux_vars(2).orig_index = 16;
M_.aux_vars(2).orig_lead_lag = -1;
M_.aux_vars(3).endo_index = 47;
M_.aux_vars(3).type = 1;
M_.aux_vars(3).orig_index = 17;
M_.aux_vars(3).orig_lead_lag = -1;
M_.aux_vars(4).endo_index = 48;
M_.aux_vars(4).type = 1;
M_.aux_vars(4).orig_index = 30;
M_.aux_vars(4).orig_lead_lag = -1;
M_.aux_vars(5).endo_index = 49;
M_.aux_vars(5).type = 1;
M_.aux_vars(5).orig_index = 2;
M_.aux_vars(5).orig_lead_lag = -1;
M_.aux_vars(6).endo_index = 50;
M_.aux_vars(6).type = 1;
M_.aux_vars(6).orig_index = 8;
M_.aux_vars(6).orig_lead_lag = -1;
M_.aux_vars(7).endo_index = 51;
M_.aux_vars(7).type = 1;
M_.aux_vars(7).orig_index = 27;
M_.aux_vars(7).orig_lead_lag = -1;
M_.aux_vars(8).endo_index = 52;
M_.aux_vars(8).type = 1;
M_.aux_vars(8).orig_index = 31;
M_.aux_vars(8).orig_lead_lag = -1;
M_.aux_vars(9).endo_index = 53;
M_.aux_vars(9).type = 1;
M_.aux_vars(9).orig_index = 31;
M_.aux_vars(9).orig_lead_lag = -2;
M_.aux_vars(10).endo_index = 54;
M_.aux_vars(10).type = 1;
M_.aux_vars(10).orig_index = 32;
M_.aux_vars(10).orig_lead_lag = -1;
M_.aux_vars(11).endo_index = 55;
M_.aux_vars(11).type = 1;
M_.aux_vars(11).orig_index = 32;
M_.aux_vars(11).orig_lead_lag = -2;
M_.aux_vars(12).endo_index = 56;
M_.aux_vars(12).type = 1;
M_.aux_vars(12).orig_index = 33;
M_.aux_vars(12).orig_lead_lag = -1;
M_.aux_vars(13).endo_index = 57;
M_.aux_vars(13).type = 1;
M_.aux_vars(13).orig_index = 33;
M_.aux_vars(13).orig_lead_lag = -2;
M_.aux_vars(14).endo_index = 58;
M_.aux_vars(14).type = 1;
M_.aux_vars(14).orig_index = 34;
M_.aux_vars(14).orig_lead_lag = -1;
M_.aux_vars(15).endo_index = 59;
M_.aux_vars(15).type = 1;
M_.aux_vars(15).orig_index = 34;
M_.aux_vars(15).orig_lead_lag = -2;
M_.aux_vars(16).endo_index = 60;
M_.aux_vars(16).type = 1;
M_.aux_vars(16).orig_index = 35;
M_.aux_vars(16).orig_lead_lag = -1;
M_.aux_vars(17).endo_index = 61;
M_.aux_vars(17).type = 1;
M_.aux_vars(17).orig_index = 35;
M_.aux_vars(17).orig_lead_lag = -2;
M_.aux_vars(18).endo_index = 62;
M_.aux_vars(18).type = 1;
M_.aux_vars(18).orig_index = 36;
M_.aux_vars(18).orig_lead_lag = -1;
M_.aux_vars(19).endo_index = 63;
M_.aux_vars(19).type = 1;
M_.aux_vars(19).orig_index = 36;
M_.aux_vars(19).orig_lead_lag = -2;
M_.aux_vars(20).endo_index = 64;
M_.aux_vars(20).type = 1;
M_.aux_vars(20).orig_index = 37;
M_.aux_vars(20).orig_lead_lag = -1;
M_.aux_vars(21).endo_index = 65;
M_.aux_vars(21).type = 1;
M_.aux_vars(21).orig_index = 37;
M_.aux_vars(21).orig_lead_lag = -2;
options_.varobs = [];
options_.varobs = 'Y';
options_.varobs_id = [ 25  ];
M_.Sigma_e = zeros(3, 3);
M_.Correlation_matrix = eye(3, 3);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = 1;
options_.block=0;
options_.bytecode=0;
options_.use_dll=0;
erase_compiled_function('model_static');
erase_compiled_function('model_dynamic');
M_.lead_lag_incidence = [
 0 40 0;
 1 41 0;
 2 42 105;
 0 43 0;
 0 44 106;
 0 45 107;
 0 46 108;
 3 47 0;
 0 48 109;
 0 49 110;
 0 50 0;
 0 51 111;
 0 52 112;
 4 53 0;
 5 54 0;
 6 55 0;
 7 56 0;
 0 57 0;
 0 58 0;
 0 59 0;
 0 60 0;
 0 61 0;
 0 62 0;
 0 63 0;
 0 64 0;
 0 65 0;
 8 66 0;
 9 67 0;
 10 68 113;
 11 69 0;
 12 70 0;
 13 71 0;
 14 72 0;
 15 73 0;
 16 74 0;
 17 75 0;
 18 76 0;
 0 77 0;
 0 78 0;
 0 79 0;
 0 80 0;
 0 81 0;
 0 82 0;
 0 83 0;
 19 84 0;
 20 85 0;
 21 86 0;
 22 87 0;
 23 88 0;
 24 89 0;
 25 90 0;
 26 91 0;
 27 92 0;
 28 93 0;
 29 94 0;
 30 95 0;
 31 96 0;
 32 97 0;
 33 98 0;
 34 99 0;
 35 100 0;
 36 101 0;
 37 102 0;
 38 103 0;
 39 104 0;]';
M_.nstatic = 19;
M_.nfwrd   = 7;
M_.npred   = 37;
M_.nboth   = 2;
M_.nsfwrd   = 9;
M_.nspred   = 39;
M_.ndynamic   = 46;
M_.equations_tags = {
  1 , 'name' , 'Market tightness' ;
  2 , 'name' , 'Job finding probability' ;
  3 , 'name' , 'Vacancy filling probability' ;
  4 , 'name' , 'Relative price' ;
  5 , 'name' , 'Lagrangian multiplier' ;
  6 , 'name' , 'Firm value' ;
  7 , 'name' , 'Free entry' ;
  8 , 'name' , 'Entry technology' ;
  9 , 'name' , 'Job creation condition' ;
  10 , 'name' , 'Expected discounted difference in vacancy value' ;
  11 , 'name' , 'Value of a vacancy' ;
  12 , 'name' , 'Marginal cost of production' ;
  13 , 'name' , 'Wage equation' ;
  14 , 'name' , 'LOM of firms' ;
  15 , 'name' , 'LOM of unemployment' ;
  16 , 'name' , 'LOM of vacancies' ;
  17 , 'name' , 'Aggregate separation rate' ;
  18 , 'name' , 'Aggregate labor' ;
  19 , 'name' , 'Composition of labor' ;
  20 , 'name' , 'Retail output: resources' ;
  21 , 'name' , 'Sunk vacancy posting costs' ;
  22 , 'name' , 'Retail output: expenditure' ;
  23 , 'name' , 'Gross output: expenditure' ;
  24 , 'name' , 'Gross output: income' ;
  25 , 'name' , 'GDP' ;
  26 , 'name' , 'Labor share' ;
  27 , 'name' , 'Labor productivity (data consistent)' ;
  28 , 'name' , 'Labor productivity process' ;
  29 , 'name' , 'Separation rate process' ;
  30 , 'name' , 'Product line destruction process' ;
  31 , 'name' , 'Unemployment observation' ;
  32 , 'name' , 'Vacancy observation' ;
  33 , 'name' , 'Job separation observation' ;
  34 , 'name' , 'Job finding rate' ;
  35 , 'name' , 'Business destruction observation' ;
  36 , 'name' , 'Business formation observation' ;
  37 , 'name' , 'Labor productivity observation' ;
  38 , 'name' , 'Lag unemployment observation' ;
  39 , 'name' , 'Lag vacancy observation' ;
  40 , 'name' , 'Job separation observation' ;
  41 , 'name' , 'Job finding rate' ;
  42 , 'name' , 'Lag business destruction observation' ;
  43 , 'name' , 'Lag business formation observation' ;
  44 , 'name' , 'Lag labor productivity observation' ;
};
M_.static_and_dynamic_models_differ = 0;
M_.exo_names_orig_ord = [1:3];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(65, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(3, 1);
M_.params = NaN(21, 1);
M_.NNZDerivatives = zeros(3, 1);
M_.NNZDerivatives(1) = 202;
M_.NNZDerivatives(2) = -1;
M_.NNZDerivatives(3) = -1;
resid;
steady;
oo_.dr.eigval = check(M_,options_,oo_);
%
% SHOCKS instructions
%
make_ex_;
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = 1;
M_.Sigma_e(2, 2) = 1;
M_.Sigma_e(3, 3) = 1;
addpath('DynareUtilites');
global estim_params_
estim_params_.var_exo = [];
estim_params_.var_endo = [];
estim_params_.corrx = [];
estim_params_.corrn = [];
estim_params_.param_vals = [];
estim_params_.param_vals = [estim_params_.param_vals; 1, NaN, (-Inf), Inf, 2, 1.0, 0.5, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 2, NaN, (-Inf), Inf, 1, 0.7, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 3, NaN, (-Inf), Inf, 2, 2.0, 1.0, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 4, NaN, (-Inf), Inf, 1, 0.5, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 5, NaN, (-Inf), Inf, 1, 0.8, 0.10, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 6, NaN, (-Inf), Inf, 1, 0.6, 0.20, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 7, NaN, (-Inf), Inf, 1, 0.9, 0.05, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 8, NaN, (-Inf), Inf, 4, 0.01, 0.005, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 9, NaN, (-Inf), Inf, 4, 0.04, 0.02, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 10, NaN, (-Inf), Inf, 4, 0.04, 0.02, NaN, NaN, NaN ];
do_imp_resp_matching=1;                  
if do_imp_resp_matching==1,
addpath('DynareImpRespMatching');     
get_empirical_moments;                
end;
options_.mh_conf_sig    = 0.95;
options_.prior_interval = 0.95;
options_.conf_sig       = 0.95;
options_.first_obs = 1;
options_.lik_init = 1;
options_.mh_drop = 0.50;
options_.mh_init_scale = 0.5;
options_.mh_jscale = 0.5;
options_.mh_nblck = 1;
options_.mh_replic = 10000;
options_.mode_compute = 0;
options_.nograph = 1;
options_.order = 1;
options_.prior_trunc = 0;
options_.datafile = 'dummy_data';
options_.mode_file = 'model_mh_mode';
var_list_=[];
dynare_estimation(var_list_);
load model_mh_mode.mat;
for ii=1:1:length(xparam1)
para_idx = find(strcmp(M_.param_names, char(parameter_names(ii))));
M_.params(para_idx)=xparam1(ii);
end
model_steadystate([],[]);
options_.nofunctions = 1;
options_.noprint = 1;
options_.order = 1;
var_list_=[];
var_list_ = 'u_obs';
var_list_ = char(var_list_, 'v_obs');
var_list_ = char(var_list_, 'tau_obs');
var_list_ = char(var_list_, 'f_obs');
var_list_ = char(var_list_, 'delta_obs');
var_list_ = char(var_list_, 'bf_obs');
var_list_ = char(var_list_, 'lp_obs');
info = stoch_simul(var_list_);
stack_model_moments;
Data_vs_Model = [Values', model_moments];
save results;
delete *.eps;
save('model_results.mat', 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save('model_results.mat', 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save('model_results.mat', 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save('model_results.mat', 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save('model_results.mat', 'estimation_info', '-append');
end


disp(['Total computing time : ' dynsec2hms(toc) ]);
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
diary off
