function [ys_, params, info] = steadystate(ys_, exo_, params)
% Steady state generated by Dynare preprocessor
    info = 0;
    r_ss=(1-params(2))/params(2);
    ys_(7)=params(5)/(1-params(3));
    ys_(8)=params(6)/(1-params(3));
    ys_(6)=ys_(7)/ys_(8);
    ys_(5)=params(4)/(params(4)+(1-params(3))*ys_(7));
    ys_(4)=ys_(6)*ys_(5);
    ys_(3)=params(3)*(1+ys_(4)-ys_(5));
    ys_(1)=(1-params(3))*ys_(8)*(1-params(8))*(params(1)-params(9))/((1-params(3))*ys_(8)*(1-params(8))+r_ss+params(4)+ys_(7)*params(8));
    ys_(2)=params(8)*(params(1)-ys_(1)+ys_(1)*ys_(6)/(1-params(3)))+(1-params(8))*params(9);
    ys_(9)=0;
    ys_(10)=0;
    ys_(11)=0;
    ys_(12)=0;
    ys_(13)=0;
    ys_(14)=0;
    ys_(15)=0;
    ys_(16)=0;
    ys_(17)=0;
    x_imp=0;
    ys_(19)=0;
    ys_(20)=0;
    % Auxiliary equations
ys_(22)=ys_(12);
ys_(23)=ys_(14);
end
