%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

if isoctave || matlab_ver_less_than('8.6')
    clear all
else
    clearvars -global
    clear_persistent_variables(fileparts(which('dynare')), false)
end
tic0 = tic;
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'baseline_alt';
M_.dynare_version = '5.4';
oo_.dynare_version = '5.4';
options_.dynare_version = '5.4';
%
% Some global variables initialization
%
global_initialization;
M_.exo_names = cell(1,1);
M_.exo_names_tex = cell(1,1);
M_.exo_names_long = cell(1,1);
M_.exo_names(1) = {'e_z'};
M_.exo_names_tex(1) = {'{e_z}'};
M_.exo_names_long(1) = {'technology shock'};
M_.endo_names = cell(37,1);
M_.endo_names_tex = cell(37,1);
M_.endo_names_long = cell(37,1);
M_.endo_names(1) = {'Q'};
M_.endo_names_tex(1) = {'{Q}'};
M_.endo_names_long(1) = {'value of vacancy'};
M_.endo_names(2) = {'K'};
M_.endo_names_tex(2) = {'{K}'};
M_.endo_names_long(2) = {'expected discounted difference in vacancy value'};
M_.endo_names(3) = {'w'};
M_.endo_names_tex(3) = {'{w}'};
M_.endo_names_long(3) = {'wage'};
M_.endo_names(4) = {'e'};
M_.endo_names_tex(4) = {'{e}'};
M_.endo_names_long(4) = {'new vacancies'};
M_.endo_names(5) = {'v'};
M_.endo_names_tex(5) = {'{v}'};
M_.endo_names_long(5) = {'vacancy stock'};
M_.endo_names(6) = {'u'};
M_.endo_names_tex(6) = {'{u}'};
M_.endo_names_long(6) = {'unemployment'};
M_.endo_names(7) = {'theta'};
M_.endo_names_tex(7) = {'{theta}'};
M_.endo_names_long(7) = {'market tightness'};
M_.endo_names(8) = {'f'};
M_.endo_names_tex(8) = {'{f}'};
M_.endo_names_long(8) = {'job finding rate'};
M_.endo_names(9) = {'q'};
M_.endo_names_tex(9) = {'{q}'};
M_.endo_names_long(9) = {'vacancy filling rate'};
M_.endo_names(10) = {'N'};
M_.endo_names_tex(10) = {'{N}'};
M_.endo_names_long(10) = {'number of firms'};
M_.endo_names(11) = {'N_e'};
M_.endo_names_tex(11) = {'{N_e}'};
M_.endo_names_long(11) = {'number of new businesses'};
M_.endo_names(12) = {'p'};
M_.endo_names_tex(12) = {'{p}'};
M_.endo_names_long(12) = {'relative price'};
M_.endo_names(13) = {'w_R'};
M_.endo_names_tex(13) = {'{w_R}'};
M_.endo_names_long(13) = {'recruiter payment'};
M_.endo_names(14) = {'nu_f'};
M_.endo_names_tex(14) = {'{nu_f}'};
M_.endo_names_long(14) = {'retailer firm value'};
M_.endo_names(15) = {'d_f'};
M_.endo_names_tex(15) = {'{d_f}'};
M_.endo_names_long(15) = {'dividend'};
M_.endo_names(16) = {'Y_c'};
M_.endo_names_tex(16) = {'{Y_c}'};
M_.endo_names_long(16) = {'retail output'};
M_.endo_names(17) = {'C'};
M_.endo_names_tex(17) = {'{C}'};
M_.endo_names_long(17) = {'consumption'};
M_.endo_names(18) = {'Omega'};
M_.endo_names_tex(18) = {'{\Omega}'};
M_.endo_names_long(18) = {'sunk entry costs of investment'};
M_.endo_names(19) = {'lam'};
M_.endo_names_tex(19) = {'{\lambda}'};
M_.endo_names_long(19) = {'Marginal utility of consumption'};
M_.endo_names(20) = {'Y'};
M_.endo_names_tex(20) = {'{Y}'};
M_.endo_names_long(20) = {'aggregate output'};
M_.endo_names(21) = {'L'};
M_.endo_names_tex(21) = {'{L}'};
M_.endo_names_long(21) = {'total labor'};
M_.endo_names(22) = {'L_e'};
M_.endo_names_tex(22) = {'{L_e}'};
M_.endo_names_long(22) = {'Labor in entry'};
M_.endo_names(23) = {'L_c'};
M_.endo_names_tex(23) = {'{L_c}'};
M_.endo_names_long(23) = {'Labor in consumption'};
M_.endo_names(24) = {'labor_share_obs'};
M_.endo_names_tex(24) = {'labor\_share\_obs'};
M_.endo_names_long(24) = {'labor_share_obs'};
M_.endo_names(25) = {'theta_z'};
M_.endo_names_tex(25) = {'{\theta_z}'};
M_.endo_names_long(25) = {'technology shock'};
M_.endo_names(26) = {'z_obs_m'};
M_.endo_names_tex(26) = {'z\_obs\_m'};
M_.endo_names_long(26) = {'z_obs_m'};
M_.endo_names(27) = {'z_obs'};
M_.endo_names_tex(27) = {'z\_obs'};
M_.endo_names_long(27) = {'z_obs'};
M_.endo_names(28) = {'u_obs'};
M_.endo_names_tex(28) = {'u\_obs'};
M_.endo_names_long(28) = {'u_obs'};
M_.endo_names(29) = {'v_obs'};
M_.endo_names_tex(29) = {'v\_obs'};
M_.endo_names_long(29) = {'v_obs'};
M_.endo_names(30) = {'u_imp'};
M_.endo_names_tex(30) = {'u\_imp'};
M_.endo_names_long(30) = {'u_imp'};
M_.endo_names(31) = {'v_imp'};
M_.endo_names_tex(31) = {'v\_imp'};
M_.endo_names_long(31) = {'v_imp'};
M_.endo_names(32) = {'theta_imp'};
M_.endo_names_tex(32) = {'theta\_imp'};
M_.endo_names_long(32) = {'theta_imp'};
M_.endo_names(33) = {'e_imp'};
M_.endo_names_tex(33) = {'e\_imp'};
M_.endo_names_long(33) = {'e_imp'};
M_.endo_names(34) = {'N_imp'};
M_.endo_names_tex(34) = {'N\_imp'};
M_.endo_names_long(34) = {'N_imp'};
M_.endo_names(35) = {'N_e_imp'};
M_.endo_names_tex(35) = {'N\_e\_imp'};
M_.endo_names_long(35) = {'N_e_imp'};
M_.endo_names(36) = {'C_imp'};
M_.endo_names_tex(36) = {'C\_imp'};
M_.endo_names_long(36) = {'C_imp'};
M_.endo_names(37) = {'AUX_ENDO_LAG_25_1'};
M_.endo_names_tex(37) = {'AUX\_ENDO\_LAG\_25\_1'};
M_.endo_names_long(37) = {'AUX_ENDO_LAG_25_1'};
M_.endo_partitions = struct();
M_.endo_partitions.lone_name = { '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' '' 'Labor share' '' '' '' '' '' '' '' '' '' '' '' '' '' };
M_.param_names = cell(14,1);
M_.param_names_tex = cell(14,1);
M_.param_names_long = cell(14,1);
M_.param_names(1) = {'w_ss'};
M_.param_names_tex(1) = {'{w_ss}'};
M_.param_names_long(1) = {'Steady-state wage'};
M_.param_names(2) = {'beta'};
M_.param_names_tex(2) = {'{\beta}'};
M_.param_names_long(2) = {'Discount factor'};
M_.param_names(3) = {'delta'};
M_.param_names_tex(3) = {'{\delta}'};
M_.param_names_long(3) = {'Product destruction rate'};
M_.param_names(4) = {'epsi'};
M_.param_names_tex(4) = {'{\varepsilon}'};
M_.param_names_long(4) = {'elasticity of substitution'};
M_.param_names(5) = {'sigma'};
M_.param_names_tex(5) = {'{\sigma}'};
M_.param_names_long(5) = {'inverse of intertemporal elasticity of substitution'};
M_.param_names(6) = {'tau'};
M_.param_names_tex(6) = {'{\tau}'};
M_.param_names_long(6) = {'Aggregate separation rate'};
M_.param_names(7) = {'fbar'};
M_.param_names_tex(7) = {'fbar'};
M_.param_names_long(7) = {'fbar'};
M_.param_names(8) = {'qbar'};
M_.param_names_tex(8) = {'{\overline{q}}'};
M_.param_names_long(8) = {'Mean vacancy filling rate'};
M_.param_names(9) = {'xi_inv'};
M_.param_names_tex(9) = {'{1/\xi}'};
M_.param_names_long(9) = {'Inverse elasticity of entrants to vacancy value'};
M_.param_names(10) = {'phi'};
M_.param_names_tex(10) = {'\phi'};
M_.param_names_long(10) = {'Worker bargaining power'};
M_.param_names(11) = {'b_ratio'};
M_.param_names_tex(11) = {'b'};
M_.param_names_long(11) = {'Replacement ratio: unemployment benefits to wages'};
M_.param_names(12) = {'eta_L'};
M_.param_names_tex(12) = {'\eta_L'};
M_.param_names_long(12) = {'Elasticity of matching function with respect to unemployment'};
M_.param_names(13) = {'N_ss'};
M_.param_names_tex(13) = {'{N_{ss}}'};
M_.param_names_long(13) = {'N_ss'};
M_.param_names(14) = {'rho_z'};
M_.param_names_tex(14) = {'{\rho_z}'};
M_.param_names_long(14) = {'persistence technology shock'};
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 1;
M_.endo_nbr = 37;
M_.param_nbr = 14;
M_.orig_endo_nbr = 36;
M_.aux_vars(1).endo_index = 37;
M_.aux_vars(1).type = 1;
M_.aux_vars(1).orig_index = 26;
M_.aux_vars(1).orig_lead_lag = -1;
M_.aux_vars(1).orig_expr = 'z_obs_m(-1)';
M_ = setup_solvers(M_);
M_.Sigma_e = zeros(1, 1);
M_.Correlation_matrix = eye(1, 1);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = true;
M_.det_shocks = [];
M_.surprise_shocks = [];
M_.heteroskedastic_shocks.Qvalue_orig = [];
M_.heteroskedastic_shocks.Qscale_orig = [];
options_.linear = false;
options_.block = false;
options_.bytecode = false;
options_.use_dll = false;
M_.orig_eq_nbr = 36;
M_.eq_nbr = 37;
M_.ramsey_eq_nbr = 0;
M_.set_auxiliary_variables = exist(['./+' M_.fname '/set_auxiliary_variables.m'], 'file') == 2;
M_.epilogue_names = {};
M_.epilogue_var_list_ = {};
M_.orig_maximum_endo_lag = 2;
M_.orig_maximum_endo_lead = 1;
M_.orig_maximum_exo_lag = 0;
M_.orig_maximum_exo_lead = 0;
M_.orig_maximum_exo_det_lag = 0;
M_.orig_maximum_exo_det_lead = 0;
M_.orig_maximum_lag = 2;
M_.orig_maximum_lead = 1;
M_.orig_maximum_lag_with_diffs_expanded = 2;
M_.lead_lag_incidence = [
 0 10 47;
 0 11 48;
 0 12 49;
 0 13 0;
 1 14 0;
 2 15 0;
 0 16 0;
 3 17 0;
 4 18 50;
 5 19 0;
 6 20 0;
 0 21 0;
 0 22 51;
 0 23 52;
 0 24 53;
 0 25 0;
 0 26 0;
 0 27 0;
 0 28 54;
 0 29 0;
 0 30 0;
 0 31 0;
 0 32 0;
 0 33 0;
 7 34 0;
 8 35 0;
 0 36 0;
 0 37 0;
 0 38 0;
 0 39 0;
 0 40 0;
 0 41 0;
 0 42 0;
 0 43 0;
 0 44 0;
 0 45 0;
 9 46 0;]';
M_.nstatic = 21;
M_.nfwrd   = 7;
M_.npred   = 8;
M_.nboth   = 1;
M_.nsfwrd   = 8;
M_.nspred   = 9;
M_.ndynamic   = 16;
M_.dynamic_tmp_nbr = [21; 15; 0; 0; ];
M_.model_local_variables_dynamic_tt_idxs = {
};
M_.equations_tags = {
  1 , 'name' , 'Job creation condition' ;
  2 , 'name' , 'Marginal revenue product' ;
  3 , 'name' , 'Wage equation' ;
  4 , 'name' , 'Value of a vacancy' ;
  5 , 'name' , 'Expected discounted difference in vacancy value' ;
  6 , 'name' , 'Market tightness' ;
  7 , 'name' , 'Job finding probability' ;
  8 , 'name' , 'Vacancy filling probability' ;
  9 , 'name' , 'Aggregate labor' ;
  10 , 'name' , 'Composition of labor' ;
  11 , 'name' , 'Relative price' ;
  12 , 'name' , 'Lagrangian multiplier' ;
  13 , 'name' , 'Firm value' ;
  14 , 'name' , 'Retail output: resources' ;
  15 , 'name' , 'Retail output: expenditure' ;
  16 , 'name' , 'Sunk vacancy posting costs' ;
  17 , 'name' , 'Business entrants' ;
  18 , 'mame' , 'Firm value relative to price' ;
  18 , 'name' , 'nu_f' ;
  19 , 'name' , 'Output: expenditure' ;
  20 , 'name' , 'Output: income' ;
  21 , 'name' , 'LOM of vacancies' ;
  22 , 'name' , 'LOM of unemployment' ;
  23 , 'name' , 'LOM of firms' ;
  24 , 'name' , 'labor share' ;
  25 , 'name' , 'Aggregate separation rate' ;
  26 , 'name' , 'z_obs' ;
  27 , 'name' , 'u_obs' ;
  28 , 'name' , 'v_obs' ;
  29 , 'name' , 'u_imp' ;
  30 , 'name' , 'v_imp' ;
  31 , 'name' , 'theta_imp' ;
  32 , 'name' , 'e_imp' ;
  33 , 'name' , 'N_imp' ;
  34 , 'name' , 'N_e_imp' ;
  35 , 'name' , 'C_imp' ;
  36 , 'name' , 'Labor productivity process' ;
};
M_.mapping.Q.eqidx = [4 5 ];
M_.mapping.K.eqidx = [1 3 5 ];
M_.mapping.w.eqidx = [1 3 24 ];
M_.mapping.e.eqidx = [4 16 21 32 ];
M_.mapping.v.eqidx = [6 21 28 30 ];
M_.mapping.u.eqidx = [6 9 21 22 27 29 ];
M_.mapping.theta.eqidx = [2 3 4 6 7 8 14 16 17 18 31 ];
M_.mapping.f.eqidx = [7 22 ];
M_.mapping.q.eqidx = [1 2 4 8 14 16 17 18 21 ];
M_.mapping.N.eqidx = [11 20 23 33 ];
M_.mapping.N_e.eqidx = [17 19 23 34 ];
M_.mapping.p.eqidx = [2 11 14 18 ];
M_.mapping.w_R.eqidx = [1 2 3 20 ];
M_.mapping.nu_f.eqidx = [13 18 19 ];
M_.mapping.d_f.eqidx = [13 20 ];
M_.mapping.Y_c.eqidx = [14 15 19 ];
M_.mapping.C.eqidx = [12 15 35 ];
M_.mapping.Omega.eqidx = [15 16 ];
M_.mapping.lam.eqidx = [1 5 12 13 ];
M_.mapping.Y.eqidx = [19 20 24 ];
M_.mapping.L.eqidx = [9 10 20 24 ];
M_.mapping.L_e.eqidx = [10 17 ];
M_.mapping.L_c.eqidx = [10 14 ];
M_.mapping.labor_share_obs.eqidx = [24 ];
M_.mapping.theta_z.eqidx = [2 14 17 25 36 ];
M_.mapping.z_obs_m.eqidx = [25 26 ];
M_.mapping.z_obs.eqidx = [26 ];
M_.mapping.u_obs.eqidx = [27 ];
M_.mapping.v_obs.eqidx = [28 ];
M_.mapping.u_imp.eqidx = [29 ];
M_.mapping.v_imp.eqidx = [30 ];
M_.mapping.theta_imp.eqidx = [31 ];
M_.mapping.e_imp.eqidx = [32 ];
M_.mapping.N_imp.eqidx = [33 ];
M_.mapping.N_e_imp.eqidx = [34 ];
M_.mapping.C_imp.eqidx = [35 ];
M_.mapping.e_z.eqidx = [36 ];
M_.static_and_dynamic_models_differ = false;
M_.has_external_function = false;
M_.state_var = [5 6 8 9 10 11 25 26 37 ];
M_.exo_names_orig_ord = [1:1];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(37, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(1, 1);
M_.params = NaN(14, 1);
M_.endo_trends = struct('deflator', cell(37, 1), 'log_deflator', cell(37, 1), 'growth_factor', cell(37, 1), 'log_growth_factor', cell(37, 1));
M_.NNZDerivatives = [123; -1; -1; ];
M_.static_tmp_nbr = [19; 15; 0; 0; ];
M_.model_local_variables_static_tt_idxs = {
};
M_.params(1) = 1.0;
w_ss = M_.params(1);
M_.params(2) = 0.99673;
beta = M_.params(2);
M_.params(9) = 0.5;
xi_inv = M_.params(9);
M_.params(3) = 0.00514;
delta = M_.params(3);
M_.params(6) = 0.031;
tau = M_.params(6);
M_.params(10) = 0.6;
phi = M_.params(10);
M_.params(7) = 0.41;
fbar = M_.params(7);
M_.params(8) = 0.8;
qbar = M_.params(8);
M_.params(13) = 1.0;
N_ss = M_.params(13);
M_.params(4) = 100.0;
epsi = M_.params(4);
M_.params(5) = 1.0;
sigma = M_.params(5);
M_.params(11) = 0.71;
b_ratio = M_.params(11);
M_.params(12) = 0.6;
eta_L = M_.params(12);
M_.params(14) = 0.0;
rho_z = M_.params(14);
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = 4.900000000000001e-05;
resid;
steady;
oo_.dr.eigval = check(M_,options_,oo_);
options_.irf = 1000;
options_.nofunctions = true;
options_.order = 1;
options_.periods = 0;
var_list_ = {'u_obs';'v_obs';'z_obs';'theta_z';'u_imp';'v_imp';'theta_imp';'e_imp';'N_imp';'N_e_imp';'C_imp';'labor_share_obs';'L_c';'L_e'};
[info, oo_, options_, M_] = stoch_simul(M_, options_, oo_, var_list_);


oo_.time = toc(tic0);
disp(['Total computing time : ' dynsec2hms(oo_.time) ]);
if ~exist([M_.dname filesep 'Output'],'dir')
    mkdir(M_.dname,'Output');
end
save([M_.dname filesep 'Output' filesep 'baseline_alt_results.mat'], 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'baseline_alt_results.mat'], 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'baseline_alt_results.mat'], 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'baseline_alt_results.mat'], 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'baseline_alt_results.mat'], 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'baseline_alt_results.mat'], 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'baseline_alt_results.mat'], 'oo_recursive_', '-append');
end
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
