%
% Status : main Dynare file
%
% Warning : this file is generated automatically by Dynare
%           from model file (.mod)

if isoctave || matlab_ver_less_than('8.6')
    clear all
else
    clearvars -global
    clear_persistent_variables(fileparts(which('dynare')), false)
end
tic0 = tic;
% Define global variables.
global M_ options_ oo_ estim_params_ bayestopt_ dataset_ dataset_info estimation_info ys0_ ex0_
options_ = [];
M_.fname = 'baseline_est';
M_.dynare_version = '5.4';
oo_.dynare_version = '5.4';
options_.dynare_version = '5.4';
%
% Some global variables initialization
%
global_initialization;
M_.exo_names = cell(5,1);
M_.exo_names_tex = cell(5,1);
M_.exo_names_long = cell(5,1);
M_.exo_names(1) = {'e_z'};
M_.exo_names_tex(1) = {'{e_z}'};
M_.exo_names_long(1) = {'technology shock'};
M_.exo_names(2) = {'e_b'};
M_.exo_names_tex(2) = {'{e_{b}}'};
M_.exo_names_long(2) = {'discount factor shock'};
M_.exo_names(3) = {'e_phi'};
M_.exo_names_tex(3) = {'{e_{phi,L}}'};
M_.exo_names_long(3) = {'wage markup shock'};
M_.exo_names(4) = {'e_F'};
M_.exo_names_tex(4) = {'{e_F}'};
M_.exo_names_long(4) = {'vacancy supply shock'};
M_.exo_names(5) = {'e_A'};
M_.exo_names_tex(5) = {'{e_F}'};
M_.exo_names_long(5) = {'matching efficiency shock'};
M_.endo_names = cell(49,1);
M_.endo_names_tex = cell(49,1);
M_.endo_names_long = cell(49,1);
M_.endo_names(1) = {'Q'};
M_.endo_names_tex(1) = {'{Q}'};
M_.endo_names_long(1) = {'value of vacancy'};
M_.endo_names(2) = {'K'};
M_.endo_names_tex(2) = {'{K}'};
M_.endo_names_long(2) = {'expected discounted difference in vacancy value'};
M_.endo_names(3) = {'w'};
M_.endo_names_tex(3) = {'{w}'};
M_.endo_names_long(3) = {'wage'};
M_.endo_names(4) = {'e'};
M_.endo_names_tex(4) = {'{e}'};
M_.endo_names_long(4) = {'new vacancies'};
M_.endo_names(5) = {'v'};
M_.endo_names_tex(5) = {'{v}'};
M_.endo_names_long(5) = {'vacancy stock'};
M_.endo_names(6) = {'u'};
M_.endo_names_tex(6) = {'{u}'};
M_.endo_names_long(6) = {'unemployment'};
M_.endo_names(7) = {'theta'};
M_.endo_names_tex(7) = {'{theta}'};
M_.endo_names_long(7) = {'market tightness'};
M_.endo_names(8) = {'f'};
M_.endo_names_tex(8) = {'{f}'};
M_.endo_names_long(8) = {'job finding rate'};
M_.endo_names(9) = {'q'};
M_.endo_names_tex(9) = {'{q}'};
M_.endo_names_long(9) = {'vacancy filling rate'};
M_.endo_names(10) = {'N'};
M_.endo_names_tex(10) = {'{N}'};
M_.endo_names_long(10) = {'number of firms'};
M_.endo_names(11) = {'N_e'};
M_.endo_names_tex(11) = {'{N_e}'};
M_.endo_names_long(11) = {'number of new businesses'};
M_.endo_names(12) = {'p'};
M_.endo_names_tex(12) = {'{p}'};
M_.endo_names_long(12) = {'relative price'};
M_.endo_names(13) = {'w_R'};
M_.endo_names_tex(13) = {'{w_R}'};
M_.endo_names_long(13) = {'recruiter payment'};
M_.endo_names(14) = {'nu_f'};
M_.endo_names_tex(14) = {'{nu_f}'};
M_.endo_names_long(14) = {'retailer firm value'};
M_.endo_names(15) = {'d_f'};
M_.endo_names_tex(15) = {'{d_f}'};
M_.endo_names_long(15) = {'dividend'};
M_.endo_names(16) = {'Y_c'};
M_.endo_names_tex(16) = {'{Y_c}'};
M_.endo_names_long(16) = {'retail output'};
M_.endo_names(17) = {'C'};
M_.endo_names_tex(17) = {'{C}'};
M_.endo_names_long(17) = {'consumption'};
M_.endo_names(18) = {'Omega'};
M_.endo_names_tex(18) = {'{\Omega}'};
M_.endo_names_long(18) = {'sunk entry costs of investment'};
M_.endo_names(19) = {'lam'};
M_.endo_names_tex(19) = {'{\lambda}'};
M_.endo_names_long(19) = {'Marginal utility of consumption'};
M_.endo_names(20) = {'Y'};
M_.endo_names_tex(20) = {'Y'};
M_.endo_names_long(20) = {'Y'};
M_.endo_names(21) = {'Y_R'};
M_.endo_names_tex(21) = {'{Y}'};
M_.endo_names_long(21) = {'data-consistent aggregate output'};
M_.endo_names(22) = {'L'};
M_.endo_names_tex(22) = {'{L}'};
M_.endo_names_long(22) = {'total labor'};
M_.endo_names(23) = {'L_e'};
M_.endo_names_tex(23) = {'{L_e}'};
M_.endo_names_long(23) = {'Labor in entry'};
M_.endo_names(24) = {'L_c'};
M_.endo_names_tex(24) = {'{L_c}'};
M_.endo_names_long(24) = {'Labor in consumption'};
M_.endo_names(25) = {'labor_share_obs'};
M_.endo_names_tex(25) = {'labor\_share\_obs'};
M_.endo_names_long(25) = {'labor share'};
M_.endo_names(26) = {'cons_share_obs_m'};
M_.endo_names_tex(26) = {'cons\_share\_obs\_m'};
M_.endo_names_long(26) = {'consumptions share of output: monthly'};
M_.endo_names(27) = {'cons_share_obs'};
M_.endo_names_tex(27) = {'cons\_share\_obs'};
M_.endo_names_long(27) = {'consumptions share of output: quarterly'};
M_.endo_names(28) = {'theta_z'};
M_.endo_names_tex(28) = {'{\theta_z}'};
M_.endo_names_long(28) = {'technology shock'};
M_.endo_names(29) = {'theta_b'};
M_.endo_names_tex(29) = {'{\theta_b}'};
M_.endo_names_long(29) = {'discount factor shock'};
M_.endo_names(30) = {'theta_phi'};
M_.endo_names_tex(30) = {'{\theta_{\phi}}'};
M_.endo_names_long(30) = {'wage markup shock'};
M_.endo_names(31) = {'theta_F'};
M_.endo_names_tex(31) = {'{\theta_F}'};
M_.endo_names_long(31) = {'shock to vacancy supply'};
M_.endo_names(32) = {'theta_A'};
M_.endo_names_tex(32) = {'{\theta_A}'};
M_.endo_names_long(32) = {'matching efficiency shocks'};
M_.endo_names(33) = {'x'};
M_.endo_names_tex(33) = {'x'};
M_.endo_names_long(33) = {'x'};
M_.endo_names(34) = {'x_obs_m'};
M_.endo_names_tex(34) = {'x\_obs\_m'};
M_.endo_names_long(34) = {'x_obs_m'};
M_.endo_names(35) = {'x_obs'};
M_.endo_names_tex(35) = {'x\_obs'};
M_.endo_names_long(35) = {'x_obs'};
M_.endo_names(36) = {'w_obs_m'};
M_.endo_names_tex(36) = {'w\_obs\_m'};
M_.endo_names_long(36) = {'w_obs_m'};
M_.endo_names(37) = {'w_obs'};
M_.endo_names_tex(37) = {'w\_obs'};
M_.endo_names_long(37) = {'w_obs'};
M_.endo_names(38) = {'u_obs'};
M_.endo_names_tex(38) = {'u\_obs'};
M_.endo_names_long(38) = {'u_obs'};
M_.endo_names(39) = {'v_obs'};
M_.endo_names_tex(39) = {'v\_obs'};
M_.endo_names_long(39) = {'v_obs'};
M_.endo_names(40) = {'u_imp'};
M_.endo_names_tex(40) = {'u\_imp'};
M_.endo_names_long(40) = {'u_imp'};
M_.endo_names(41) = {'v_imp'};
M_.endo_names_tex(41) = {'v\_imp'};
M_.endo_names_long(41) = {'v_imp'};
M_.endo_names(42) = {'theta_imp'};
M_.endo_names_tex(42) = {'theta\_imp'};
M_.endo_names_long(42) = {'theta_imp'};
M_.endo_names(43) = {'e_imp'};
M_.endo_names_tex(43) = {'e\_imp'};
M_.endo_names_long(43) = {'e_imp'};
M_.endo_names(44) = {'N_imp'};
M_.endo_names_tex(44) = {'N\_imp'};
M_.endo_names_long(44) = {'N_imp'};
M_.endo_names(45) = {'N_e_imp'};
M_.endo_names_tex(45) = {'N\_e\_imp'};
M_.endo_names_long(45) = {'N_e_imp'};
M_.endo_names(46) = {'C_imp'};
M_.endo_names_tex(46) = {'C\_imp'};
M_.endo_names_long(46) = {'C_imp'};
M_.endo_names(47) = {'AUX_ENDO_LAG_25_1'};
M_.endo_names_tex(47) = {'AUX\_ENDO\_LAG\_25\_1'};
M_.endo_names_long(47) = {'AUX_ENDO_LAG_25_1'};
M_.endo_names(48) = {'AUX_ENDO_LAG_33_1'};
M_.endo_names_tex(48) = {'AUX\_ENDO\_LAG\_33\_1'};
M_.endo_names_long(48) = {'AUX_ENDO_LAG_33_1'};
M_.endo_names(49) = {'AUX_ENDO_LAG_35_1'};
M_.endo_names_tex(49) = {'AUX\_ENDO\_LAG\_35\_1'};
M_.endo_names_long(49) = {'AUX_ENDO_LAG_35_1'};
M_.endo_partitions = struct();
M_.param_names = cell(18,1);
M_.param_names_tex = cell(18,1);
M_.param_names_long = cell(18,1);
M_.param_names(1) = {'z'};
M_.param_names_tex(1) = {'{x}'};
M_.param_names_long(1) = {'Steady-state productivity'};
M_.param_names(2) = {'beta'};
M_.param_names_tex(2) = {'{\beta}'};
M_.param_names_long(2) = {'Discount factor'};
M_.param_names(3) = {'delta'};
M_.param_names_tex(3) = {'{\delta}'};
M_.param_names_long(3) = {'Product destruction rate'};
M_.param_names(4) = {'mu_net'};
M_.param_names_tex(4) = {'{\mu-1}'};
M_.param_names_long(4) = {'net markup'};
M_.param_names(5) = {'sigma'};
M_.param_names_tex(5) = {'{\sigma}'};
M_.param_names_long(5) = {'inverse of intertemporal elasticity of substitution'};
M_.param_names(6) = {'tau'};
M_.param_names_tex(6) = {'{\tau}'};
M_.param_names_long(6) = {'Aggregate separation rate'};
M_.param_names(7) = {'fbar'};
M_.param_names_tex(7) = {'fbar'};
M_.param_names_long(7) = {'fbar'};
M_.param_names(8) = {'qbar'};
M_.param_names_tex(8) = {'{\overline{q}}'};
M_.param_names_long(8) = {'Mean vacancy filling rate'};
M_.param_names(9) = {'xi_inv'};
M_.param_names_tex(9) = {'{1/\xi}'};
M_.param_names_long(9) = {'Inverse elasticity of entrants to vacancy value'};
M_.param_names(10) = {'b_ratio'};
M_.param_names_tex(10) = {'b'};
M_.param_names_long(10) = {'Replacement ratio: unemployment benefits to wages'};
M_.param_names(11) = {'eta_L'};
M_.param_names_tex(11) = {'\eta_L'};
M_.param_names_long(11) = {'Elasticity of matching function with respect to unemployment'};
M_.param_names(12) = {'labor_share'};
M_.param_names_tex(12) = {'labor\_share'};
M_.param_names_long(12) = {'labor_share'};
M_.param_names(13) = {'N_ss'};
M_.param_names_tex(13) = {'{N_{ss}}'};
M_.param_names_long(13) = {'N_ss'};
M_.param_names(14) = {'rho_z'};
M_.param_names_tex(14) = {'{\rho_z}'};
M_.param_names_long(14) = {'persistence technology shock'};
M_.param_names(15) = {'rho_b'};
M_.param_names_tex(15) = {'{\rho_b}'};
M_.param_names_long(15) = {'persistence discount-factor shock'};
M_.param_names(16) = {'rho_phi'};
M_.param_names_tex(16) = {'{\rho_phi}'};
M_.param_names_long(16) = {'persistence wage markup shock'};
M_.param_names(17) = {'rho_F'};
M_.param_names_tex(17) = {'{\rho_F}'};
M_.param_names_long(17) = {'persistence cost vacancy supply shock'};
M_.param_names(18) = {'rho_A'};
M_.param_names_tex(18) = {'{\rho_A}'};
M_.param_names_long(18) = {'persistence cost vacancy supply shock'};
M_.param_partitions = struct();
M_.exo_det_nbr = 0;
M_.exo_nbr = 5;
M_.endo_nbr = 49;
M_.param_nbr = 18;
M_.orig_endo_nbr = 46;
M_.aux_vars(1).endo_index = 47;
M_.aux_vars(1).type = 1;
M_.aux_vars(1).orig_index = 26;
M_.aux_vars(1).orig_lead_lag = -1;
M_.aux_vars(1).orig_expr = 'cons_share_obs_m(-1)';
M_.aux_vars(2).endo_index = 48;
M_.aux_vars(2).type = 1;
M_.aux_vars(2).orig_index = 34;
M_.aux_vars(2).orig_lead_lag = -1;
M_.aux_vars(2).orig_expr = 'x_obs_m(-1)';
M_.aux_vars(3).endo_index = 49;
M_.aux_vars(3).type = 1;
M_.aux_vars(3).orig_index = 36;
M_.aux_vars(3).orig_lead_lag = -1;
M_.aux_vars(3).orig_expr = 'w_obs_m(-1)';
options_.varobs = cell(4, 1);
options_.varobs(1)  = {'u_obs'};
options_.varobs(2)  = {'v_obs'};
options_.varobs(3)  = {'x_obs'};
options_.varobs(4)  = {'w_obs'};
options_.varobs_id = [ 38 39 35 37  ];
M_ = setup_solvers(M_);
M_.Sigma_e = zeros(5, 5);
M_.Correlation_matrix = eye(5, 5);
M_.H = 0;
M_.Correlation_matrix_ME = 1;
M_.sigma_e_is_diagonal = true;
M_.det_shocks = [];
M_.surprise_shocks = [];
M_.heteroskedastic_shocks.Qvalue_orig = [];
M_.heteroskedastic_shocks.Qscale_orig = [];
options_.linear = false;
options_.block = false;
options_.bytecode = false;
options_.use_dll = false;
M_.orig_eq_nbr = 46;
M_.eq_nbr = 49;
M_.ramsey_eq_nbr = 0;
M_.set_auxiliary_variables = exist(['./+' M_.fname '/set_auxiliary_variables.m'], 'file') == 2;
M_.epilogue_names = {};
M_.epilogue_var_list_ = {};
M_.orig_maximum_endo_lag = 2;
M_.orig_maximum_endo_lead = 1;
M_.orig_maximum_exo_lag = 0;
M_.orig_maximum_exo_lead = 0;
M_.orig_maximum_exo_det_lag = 0;
M_.orig_maximum_exo_det_lead = 0;
M_.orig_maximum_lag = 2;
M_.orig_maximum_lead = 1;
M_.orig_maximum_lag_with_diffs_expanded = 2;
M_.lead_lag_incidence = [
 0 21 70;
 0 22 71;
 1 23 72;
 0 24 0;
 2 25 0;
 3 26 0;
 0 27 0;
 4 28 0;
 5 29 73;
 6 30 0;
 7 31 0;
 8 32 0;
 0 33 74;
 0 34 75;
 0 35 76;
 0 36 0;
 0 37 0;
 0 38 0;
 0 39 77;
 0 40 0;
 0 41 0;
 0 42 0;
 0 43 0;
 0 44 0;
 0 45 0;
 9 46 0;
 0 47 0;
 10 48 0;
 11 49 0;
 12 50 0;
 13 51 0;
 14 52 0;
 15 53 0;
 16 54 0;
 0 55 0;
 17 56 0;
 0 57 0;
 0 58 0;
 0 59 0;
 0 60 0;
 0 61 0;
 0 62 0;
 0 63 0;
 0 64 0;
 0 65 0;
 0 66 0;
 18 67 0;
 19 68 0;
 20 69 0;]';
M_.nstatic = 23;
M_.nfwrd   = 6;
M_.npred   = 18;
M_.nboth   = 2;
M_.nsfwrd   = 8;
M_.nspred   = 20;
M_.ndynamic   = 26;
M_.dynamic_tmp_nbr = [23; 10; 0; 0; ];
M_.model_local_variables_dynamic_tt_idxs = {
};
M_.equations_tags = {
  1 , 'name' , 'Job creation condition' ;
  2 , 'name' , 'Marginal revenue product' ;
  3 , 'name' , 'Wage equation' ;
  4 , 'name' , 'Value of a vacancy' ;
  5 , 'name' , 'Expected discounted difference in vacancy value' ;
  6 , 'name' , 'Market tightness' ;
  7 , 'name' , 'Job finding probability' ;
  8 , 'name' , 'Vacancy filling probability' ;
  9 , 'name' , 'Aggregate labor' ;
  10 , 'name' , 'Composition of labor' ;
  11 , 'name' , 'Relative price' ;
  12 , 'name' , 'Lagrangian multiplier' ;
  13 , 'name' , 'Firm value' ;
  14 , 'name' , 'Retail output: resources' ;
  15 , 'name' , 'Retail output: expenditure' ;
  16 , 'name' , 'Sunk vacancy posting costs' ;
  17 , 'Name' , 'Business entrants' ;
  17 , 'name' , 'N_e' ;
  18 , 'Name' , 'Firm value relative to price' ;
  18 , 'name' , 'nu_f' ;
  19 , 'Name' , 'Expenditure = income' ;
  19 , 'name' , '19' ;
  20 , 'Name' , 'Output' ;
  20 , 'name' , 'Y' ;
  21 , 'Name' , 'Data-consistent output' ;
  21 , 'name' , 'Y_R' ;
  22 , 'name' , 'LOM of vacancies' ;
  23 , 'name' , 'LOM of unemployment' ;
  24 , 'name' , 'LOM of firms' ;
  25 , 'name' , 'labor productivity' ;
  26 , 'name' , 'labor share' ;
  27 , 'name' , 'consumption share' ;
  28 , 'name' , 'cons_share_obs' ;
  29 , 'name' , 'Aggregate separation rate' ;
  30 , 'name' , 'w_obs_m' ;
  31 , 'name' , 'x_obs' ;
  32 , 'name' , 'w_obs' ;
  33 , 'name' , 'u_obs' ;
  34 , 'name' , 'v_obs' ;
  35 , 'name' , 'u_imp' ;
  36 , 'name' , 'v_imp' ;
  37 , 'name' , 'theta_imp' ;
  38 , 'name' , 'e_imp' ;
  39 , 'name' , 'N_imp' ;
  40 , 'name' , 'N_e_imp' ;
  41 , 'name' , 'C_imp' ;
  42 , 'name' , 'Technology shock process' ;
  43 , 'name' , 'Discount factor process' ;
  44 , 'name' , 'Bargaining power process' ;
  45 , 'name' , 'Vacancy supply process' ;
  46 , 'name' , 'Matching efficiency process' ;
};
M_.mapping.Q.eqidx = [4 5 ];
M_.mapping.K.eqidx = [1 3 5 ];
M_.mapping.w.eqidx = [1 3 26 30 ];
M_.mapping.e.eqidx = [4 16 22 38 ];
M_.mapping.v.eqidx = [6 22 34 36 ];
M_.mapping.u.eqidx = [6 9 22 23 33 35 ];
M_.mapping.theta.eqidx = [3 6 7 8 37 ];
M_.mapping.f.eqidx = [7 23 ];
M_.mapping.q.eqidx = [1 3 4 8 16 22 ];
M_.mapping.N.eqidx = [11 19 24 39 ];
M_.mapping.N_e.eqidx = [17 19 20 24 40 ];
M_.mapping.p.eqidx = [2 3 4 11 14 16 18 21 30 ];
M_.mapping.w_R.eqidx = [1 2 3 19 ];
M_.mapping.nu_f.eqidx = [13 18 19 20 ];
M_.mapping.d_f.eqidx = [13 19 ];
M_.mapping.Y_c.eqidx = [14 15 19 20 ];
M_.mapping.C.eqidx = [12 15 27 41 ];
M_.mapping.Omega.eqidx = [15 16 ];
M_.mapping.lam.eqidx = [1 5 12 13 ];
M_.mapping.Y.eqidx = [20 21 26 27 ];
M_.mapping.Y_R.eqidx = [21 25 ];
M_.mapping.L.eqidx = [9 10 19 25 26 ];
M_.mapping.L_e.eqidx = [10 17 ];
M_.mapping.L_c.eqidx = [10 14 ];
M_.mapping.labor_share_obs.eqidx = [26 ];
M_.mapping.cons_share_obs_m.eqidx = [27 28 ];
M_.mapping.cons_share_obs.eqidx = [28 ];
M_.mapping.theta_z.eqidx = [2 14 17 42 ];
M_.mapping.theta_b.eqidx = [1 5 13 43 ];
M_.mapping.theta_phi.eqidx = [3 44 ];
M_.mapping.theta_F.eqidx = [4 16 45 ];
M_.mapping.theta_A.eqidx = [7 8 46 ];
M_.mapping.x.eqidx = [25 29 ];
M_.mapping.x_obs_m.eqidx = [29 31 ];
M_.mapping.x_obs.eqidx = [31 ];
M_.mapping.w_obs_m.eqidx = [30 32 ];
M_.mapping.w_obs.eqidx = [32 ];
M_.mapping.u_obs.eqidx = [33 ];
M_.mapping.v_obs.eqidx = [34 ];
M_.mapping.u_imp.eqidx = [35 ];
M_.mapping.v_imp.eqidx = [36 ];
M_.mapping.theta_imp.eqidx = [37 ];
M_.mapping.e_imp.eqidx = [38 ];
M_.mapping.N_imp.eqidx = [39 ];
M_.mapping.N_e_imp.eqidx = [40 ];
M_.mapping.C_imp.eqidx = [41 ];
M_.mapping.e_z.eqidx = [42 ];
M_.mapping.e_b.eqidx = [43 ];
M_.mapping.e_phi.eqidx = [44 ];
M_.mapping.e_F.eqidx = [45 ];
M_.mapping.e_A.eqidx = [46 ];
M_.static_and_dynamic_models_differ = false;
M_.has_external_function = false;
M_.state_var = [3 5 6 8 9 10 11 12 26 28 29 30 31 32 33 34 36 47 48 49 ];
M_.exo_names_orig_ord = [1:5];
M_.maximum_lag = 1;
M_.maximum_lead = 1;
M_.maximum_endo_lag = 1;
M_.maximum_endo_lead = 1;
oo_.steady_state = zeros(49, 1);
M_.maximum_exo_lag = 0;
M_.maximum_exo_lead = 0;
oo_.exo_steady_state = zeros(5, 1);
M_.params = NaN(18, 1);
M_.endo_trends = struct('deflator', cell(49, 1), 'log_deflator', cell(49, 1), 'growth_factor', cell(49, 1), 'log_growth_factor', cell(49, 1));
M_.NNZDerivatives = [165; -1; -1; ];
M_.static_tmp_nbr = [22; 10; 0; 0; ];
M_.model_local_variables_static_tt_idxs = {
};
M_.params(1) = 1.0;
z = M_.params(1);
M_.params(2) = 0.99673;
beta = M_.params(2);
M_.params(9) = 0.5;
xi_inv = M_.params(9);
M_.params(3) = 0.00514;
delta = M_.params(3);
M_.params(6) = 0.031;
tau = M_.params(6);
M_.params(7) = 0.41;
fbar = M_.params(7);
M_.params(8) = 0.8;
qbar = M_.params(8);
M_.params(12) = 0.66;
labor_share = M_.params(12);
M_.params(13) = 1.0;
N_ss = M_.params(13);
M_.params(4) = 0.3;
mu_net = M_.params(4);
M_.params(5) = 1.5;
sigma = M_.params(5);
M_.params(10) = 0.71;
b_ratio = M_.params(10);
M_.params(11) = 0.6;
eta_L = M_.params(11);
M_.params(14) = 0.979;
rho_z = M_.params(14);
M_.params(15) = 0.979;
rho_b = M_.params(15);
M_.params(16) = 0.979;
rho_phi = M_.params(16);
M_.params(17) = 0.979;
rho_F = M_.params(17);
M_.params(18) = 0.979;
rho_A = M_.params(18);
%
% SHOCKS instructions
%
M_.exo_det_length = 0;
M_.Sigma_e(1, 1) = 4.900000000000001e-05;
M_.Sigma_e(2, 2) = 5.184e-05;
M_.Sigma_e(3, 3) = 5.184e-05;
resid;
steady;
oo_.dr.eigval = check(M_,options_,oo_);
estim_params_.var_exo = zeros(0, 10);
estim_params_.var_endo = zeros(0, 10);
estim_params_.corrx = zeros(0, 11);
estim_params_.corrn = zeros(0, 11);
estim_params_.param_vals = zeros(0, 10);
estim_params_.param_vals = [estim_params_.param_vals; 10, 0.71, 0.4, 0.95, 1, 0.71, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 11, 0.6, 0.5, 0.8, 1, 0.6, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 3, 0.00514, 0.0, M_.params(6), 1, 0.00514, 0.001, 0.0, M_.params(6), NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 9, 1.0, 0.0, 20, 2, 1.0, 0.5, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 4, 0.3, 0.0, 2.0, 2, 0.3, 0.1, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 5, 1.5, 1.0, 4.0, 2, 1.5, 0.5, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 14, 0.9, 0.0001, 0.99999, 1, 0.6, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 15, 0.9, 0.01, 0.999999, 1, 0.6, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 16, 0.9, 0.01, 0.999999, 1, 0.6, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 17, 0.9, 0.01, 0.999999, 1, 0.6, 0.2, NaN, NaN, NaN ];
estim_params_.param_vals = [estim_params_.param_vals; 18, 0.9, 0.01, 0.999999, 1, 0.6, 0.2, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 1, 0.01, 0.0000001, 0.2, 4, 0.01, 0.1, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 2, 0.01, 0.00001, 0.2, 4, 0.01, 0.1, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 3, 0.01, 0.00001, 0.2, 4, 0.01, 0.1, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 4, 0.01, 0.00001, 0.2, 4, 0.01, 0.1, NaN, NaN, NaN ];
estim_params_.var_exo = [estim_params_.var_exo; 5, 0.01, 0.00001, 0.2, 4, 0.01, 0.1, NaN, NaN, NaN ];
options_.TeX=1;
options_.TeX = true;
options_.lik_init = 2;
options_.mh_drop = 0.3;
options_.mh_init_scale = 0.0001;
options_.mh_jscale = 0.001;
options_.mh_nblck = 2;
options_.mh_replic = 100000;
options_.mode_check.status = true;
options_.mode_compute = 4;
options_.nograph = true;
options_.presample = 0;
options_.prior_trunc = 0;
options_.MCMC_jumping_covariance = 'prior_variance';
options_.datafile = 'observables_u_level';
options_.optim_opt = '''MaxIter'',200';
options_.order = 1;
var_list_ = {'u_obs';'v_obs';'x_obs';'w_obs';'cons_share_obs';'theta_z';'u_imp';'v_imp';'theta_imp';'e_imp';'N_imp';'N_e_imp';'C_imp';'labor_share_obs';'L_c';'L_e'};
oo_recursive_=dynare_estimation(var_list_);
options_.irf = 80;
options_.nofunctions = true;
options_.order = 1;
options_.periods = 0;
var_list_ = {'u_obs';'v_obs';'x_obs';'w_obs';'cons_share_obs';'theta_z';'u_imp';'v_imp';'theta_imp';'e_imp';'N_imp';'N_e_imp';'C_imp';'labor_share_obs';'L_c';'L_e'};
[info, oo_, options_, M_] = stoch_simul(M_, options_, oo_, var_list_);


oo_.time = toc(tic0);
disp(['Total computing time : ' dynsec2hms(oo_.time) ]);
if ~exist([M_.dname filesep 'Output'],'dir')
    mkdir(M_.dname,'Output');
end
save([M_.dname filesep 'Output' filesep 'baseline_est_results.mat'], 'oo_', 'M_', 'options_');
if exist('estim_params_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'baseline_est_results.mat'], 'estim_params_', '-append');
end
if exist('bayestopt_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'baseline_est_results.mat'], 'bayestopt_', '-append');
end
if exist('dataset_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'baseline_est_results.mat'], 'dataset_', '-append');
end
if exist('estimation_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'baseline_est_results.mat'], 'estimation_info', '-append');
end
if exist('dataset_info', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'baseline_est_results.mat'], 'dataset_info', '-append');
end
if exist('oo_recursive_', 'var') == 1
  save([M_.dname filesep 'Output' filesep 'baseline_est_results.mat'], 'oo_recursive_', '-append');
end
if ~isempty(lastwarn)
  disp('Note: warning(s) encountered in MATLAB/Octave code')
end
